require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'

Layout/LineLength:
  Max: 80
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
RSpec/NestedGroups:
  Max: 4
  Enabled: true
